name: build-image
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - feature/handle_a_lot_of_vuln # Triggers the workflow on pushes to the main branch

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push packages to ghcr.io
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/lbi22/trivy-dojo-report-operator

      - name: Build and push to ghcr.io
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true # This is set to true to push on every trigger
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

